### ISSUE TITLE
Compiled CSS-in-JS

### ISSUE THREAD

**Issue by magne4000** [batijs/bati#134]
Add [Compiled](https://github.com/atlassian-labs/compiled).
> A familiar and performant compile time CSS-in-JS library for React

<sub>React with 👍 to upvote this ticket.</sub>

**Comment by AurelienLourot** [comment]
Maybe helpful for this task: https://github.com/nitedani/vite-plugin-compiled-react

**Comment by Kenzo-Wada** [comment]
WDYT about other zero-runtime CSS-in-JS such as vanilla-extract?

**Comment by magne4000** [comment]
@Kenzo-Wada I was thinking the same thing. You can propose other tools like this by creating a new issue.

**Comment by Kenzo-Wada** [comment]
Got it! I'll create some issues:)

**Comment by magne4000** [comment]
Fixed by #150
