### ISSUE TITLE
Use GitHub as upvoting platform

### ISSUE THREAD

**Issue by brillout** [batijs/bati#22]
Idea: using GitHub issues as upvote platform.

> Not seeing your favorite tool? [Manually integrate it](https://vike.dev/integration) and/or upvote it [here](https://github.com/batijs/bati/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Aheavy_plus_sign%3A+tool%22).

**Comment by magne4000** [comment]
Added to README
