### ISSUE TITLE
Endpoints 404 with vercel

### ISSUE THREAD

**Issue by Mozzesdev** [batijs/bati#293]
**Describe the bug**
I use an express app to have the api on the server itself it returns a 404, it's like it doesn't find the path with vercel

**To Reproduce**
Just use this preset or whatever with vercel and express and check the deploy, looks great but the other endpoints are dead
`pnpm create @batijs/app --react --tailwindcss --telefunc --express --vercel --eslint`

**Expected behavior**
The other endponts other than "*" returns will return 202 or whatever if it defined in the server

**Screenshots**
![image](https://github.com/batijs/bati/assets/82300153/85f7803e-42cf-4f47-9969-893ef8e63fa2)
![image](https://github.com/batijs/bati/assets/82300153/e4ae0062-64a6-4a0a-a0fa-2ea32ed1090b)

**Comment by magne4000** [comment]
The Vercel integration is indeed incomplete, it seems like when I'm choosing a server it is used locally but not by Vercel.

I should have a fix for tomorrow.

**Comment by magne4000** [comment]
I release a `0.0.217-beta.1` version that should fix the issue.
You can try it with `pnpm create @batijs/app@beta ...`
