### ISSUE TITLE
Could not resolve "vike-react/config" [plugin vike-esbuild]

### ISSUE THREAD

**Issue by jordyalcides** [batijs/bati#294]
**Describe the bug**
After starting a new project with the command `pnpm create @batijs/app --react`, installing dependencies and running dev mode the console shows an error
`[vike][config] Failed to transpile /pages/+config.ts because:`
`✘ [ERROR] Could not resolve "vike-react/config" [plugin vike-esbuild]`

**To Reproduce**
Steps to reproduce the behavior, run the following commands in order:
`pnpm create @batijs/app --react`
`cd my-app`
`pnpm i && pnpm run dev`

**Expected behavior**
Run dev mode without any errors

**Screenshots**
![Screenshot 2024-07-03 at 17 53 27](https://github.com/batijs/bati/assets/9451041/a01a8e75-d9cb-40fc-bfb4-4a6b14bb6eab)

**Additional context**
Using macOS Ventura 13.6.6, also I have updated node, pnpm, typescript and all libs versions to match the versions on stackblitz demo (which I know works), still the problem persists. I also tried installing the dependencies from the stackblitz lockfile.

**Comment by magne4000** [comment]
Which version of node are you using exactly?

**Comment by jordyalcides** [comment]
node version: v18.20.3
pnpm version: 9.4.0

**Comment by magne4000** [comment]
Closing in favor of https://github.com/vikejs/vike/issues/1729
