### ISSUE TITLE
Missing file "./server/vike-handler.ts"

### ISSUE THREAD

**Issue by Mozzesdev** [batijs/bati#296]
**Describe the bug**
When running a bati command in a local environment with a preset that includes express, the file "vike-handler.ts" is missing in the "./server" folder. Where it's present on the stackblitz corresponding example.
`npm create @batijs/app --react --tailwindcss  --express`

**To Reproduce**
Just execute `npm create @batijs/app --react --tailwindcss  --express` in a locale environment (Windows 11)

**Comment by magne4000** [comment]
Fix incoming as part of https://github.com/batijs/bati/pull/295
