### ISSUE TITLE
Add Unocss

### ISSUE THREAD

**Issue by alphaelf** [batijs/bati#302]
hi can we use unocss instead of tailwindcss ?

**Comment by magne4000** [comment]
Right now, the quickest way to achieve this is to select Tailwind, then once Bati CLI is executed, install UnoCSS and replace Tailwind.

You can also [request it as a feature](https://github.com/batijs/bati/discussions/categories/integration-request?discussions_q=category%3A%22Integration+request%22+is%3Aopen).
