### ISSUE TITLE
using nodemon in dev for better experience

### ISSUE THREAD

**Issue by BanDroid** [batijs/bati#36]
we could use _nodemon_ with custom `--exec` with tsx in dev command, any plan for making it this way? i made the nodemon to watch only the server directory since only in there i would change any server-related code.

i tried using ts-node, but it seems giving TS Error, using tsx is much more easier.

![IMG_20230702_182546_043](https://github.com/batijs/bati/assets/68449470/1fc8b97c-c949-4549-950e-77cf39685a16)

**Comment by brillout** [comment]
I think it's better we wait for https://github.com/brillout/vite-plugin-ssr/issues/562 instead, as it will provide a much better DX.

Closing, but if someone disagrees let me know.

**Comment by BanDroid** [comment]
> I think it's better we wait for [brillout/vite-plugin-ssr#562](https://github.com/brillout/vite-plugin-ssr/issues/562) instead, as it will provide a much better DX.
> 
> Closing, but if someone disagrees let me know.

i could wait, but for using batijs to scaffold new app, probably use nodemon as it is not the main vite-plugin-ssr boilerplate. even if i create a new app using batijs, i will use nodemon anyway and it is not efficient to do everytime creating new app

**Comment by brillout** [comment]
I agree, but I don't think it's worth it to add if if we'll remove it soon.
