### ISSUE TITLE
Standalone Boilerplate

### ISSUE THREAD

**Issue by BanDroid** [batijs/bati#52]
the starwars data in boilerplate is fetched from external data from other server, i hope it could be modified to be a simpler one that just fetching data from the project route itself.

**Comment by brillout** [comment]
Agreed. Depending on what the user is building, querying an external endpoint may actually be fitting. For example if a user has an existing Java backend and only wants to scaffold a frontend.

> I updated Bati so that when installing [`telefunc`](https://telefunc.com), it also adds a todolist example showcasing its usage.

Makes sense, as the user will then most likely want to fetch local data.

**Comment by BanDroid** [comment]
or probably add both, fetching data locally and externally woul be good ideas, because fetching the data locally, since onBeforeRender is running in server by default, some people might get confused on how to fetch the data because in client, the url origin is available by default, but then in server, the url origin is undefined which cause error for some people.

to retrieve the url origin, i had to combine `res.protocol` and `res.hostname`

**Comment by magne4000** [comment]
> to retrieve the url origin, i had to combine `req.protocol` and `req.hostname`

What do you mean by that?

**Comment by BanDroid** [comment]
> > to retrieve the url origin, i had to combine `req.protocol` and `req.hostname`
> 
> What do you mean by that?

i'm trying to fetch data locally in onBeforeRender, example is `fetch("/mypath/endpoint")` but this got error of `no address asociated with hostname /mypath/endpoint` and i had to use `fetch("http://localhost:3000/mypath/endpoint")`

`pageContext` in onBeforeRender had undefined url hostname, i had to modify pageContextInit in express-entry.ts to add new property

```javascript
const pageContextInit = {
  urlOrigin: `${req.protocol}://${req.hostname}`
}
```

this way i could do `fetch(pageContext.urlOrigin + "/mypath/endpoint")`

i hope the boilerplate would show me a proper way of fetching data locally.

**Comment by magne4000** [comment]
You should usually not call `fetch` in `onBeforeRender` to retrieve localhost information.
The only use case for which it's valid is when the API you're calling (`"/mypath/endpoint"` in your example) is defined by a different app that run on the same machine, but I'll assume that it's not the case here.

You should try to generate a boilerplate with `--telefunc`, or check https://github.com/brillout/vite-plugin-ssr/tree/main/examples/telefunc-v1/pages/index

**Comment by magne4000** [comment]
Adding some reasons why calling `fetch` on localhost from the server is a bad idea:
- Full network loop with a request + response (with potential mismatch on Origin, Hostname, Protocol, Headers, etc.)
- Unnecessary serialization
- Typing is lost

**Comment by magne4000** [comment]
> that's why i hope the boilerplate could show the proper way to get data locally in the same app

Fair enough. It will be added in the near future when [presets](https://github.com/batijs/bati/issues/23) or [wizard](https://github.com/batijs/bati/issues/26) are added.
