### ISSUE TITLE
[Bug] Solidjs + Vercel + H3 build failed + can not run telefunc server in production/build mode

### ISSUE THREAD

**Issue by harrytran998** [batijs/bati#89]
Here is the command to generate the project. Hope you can check that 😆

`pnpm create @batijs/app --solid --telefunc --h3 --vercel my-app`

1. When build project, we have some warning

```bash
9:25:34 AM [vike][Warning] You're executing prerender() but the config prerender isn't set to true
▲ [WARNING] "../../../../dist/server/importBuild.cjs" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/@brillout/vite-plugin-import-build/dist/autoImporter.js:8:53:
      8 │ ...esolve("../../../../dist/server/importBuild....
        ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/solid-js/dist/server.js" was marked as having no side effects [ignored-bare-import]

    dist/server/entries/pages_error.mjs:4:7:
      4 │ import "solid-js";
        ╵        ~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json"
  file:

    node_modules/solid-js/package.json:20:2:
      20 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

▲ [WARNING] Ignoring this import because "node_modules/solid-js/dist/server.js" was marked as having no side effects [ignored-bare-import]

    dist/server/entries/pages_star-wars_-id.mjs:6:7:
      6 │ import "solid-js";
        ╵        ~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json"
  file:

    node_modules/solid-js/package.json:20:2:
      20 │   "sideEffects": false,
         ╵   ~~~~~~~~~~~~~

3 warnings

  .vercel/output/functions/ssr_.func/index.js  506.9kb
  ```

2. In production after building the project with the command `vite preview` --> We cannot add todos list anymore 🤔

```bash
[vike][request(21)] HTTP response /_telefunc 404
```

Hope your team can check this <3 Thanks for the great of this project <3! @magne4000

**Comment by magne4000** [comment]
Hi @harrytran998 :wave:, glad you like Bati!

I release a new version (`v0.0.84`) which fixes some of the issues you listed:

- `[vike][Warning] You're executing prerender() but the config prerender isn't set to true` should no longer appear
- `preview` script has been updated to `NODE_ENV=production esno ./h3-entry.ts` so that customs routes (like telefunc) are also taken into account.

Regarding the other warnings, we need to see with @brillout how to get rid of those.
You can safely ignore the warnings for now. We'll add a comment here when we have a fix for that too.

**Comment by brillout** [comment]
I could reproduce the Rollup warnings, I'll dig into them tomorrow. The warnings don't seem to be a blocker, but let me know if it's somehow urgent.

**Comment by brillout** [comment]
The warnings will be fixed in the next release of Vike and Bati.

@harrytran998 Thanks for opening the issue, definitely let us know about other such paper cuts. We're looking forward to further polish things.

(Apologies for the delay, a couple of unexpected high prios popped up.)
